require 'bundler/setup'
Bundler.require :default

task :problem_1 do
  puts 'If we list all the natural numbers below 10 that are multiples of ' \
       '3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.'
  puts 'Find the sum of all the multiples of 3 or 5 below 1000.'

  sum = 1000.times.inject(0) do |acc, e|
    acc + (((e % 3).zero? || (e % 5).zero?) ? e : 0)
  end
  puts "The sum is #{sum}"
end

task :problem_2 do
  puts 'Each new term in the Fibonacci sequence is generated by adding the ' \
       'previous two terms. By starting with 1 and 2, the first 10 terms ' \
       'will be:'
  puts '1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...'
  puts 'By considering the terms in the Fibonacci sequence whose values ' \
       'do not exceed four million, find the sum of the even-valued terms.'

  def fib(n)
    return 0 if n <= 0
    n == 1 ? 1 : fib(n - 2) + fib(n - 1)
  end

  acc = []
  index = 1
  while true
    el = fib(index)
    el >= 4_000_000 ? break : acc << el
    index += 1
  end
  sum = acc.select { |x| (x % 2).zero? }.inject(:+)
  puts "The sum is #{sum}"
end
