require 'bundler/setup'
Bundler.require :default

task :problem_1 do
  puts 'If we list all the natural numbers below 10 that are multiples of ' \
       '3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.'
  puts 'Find the sum of all the multiples of 3 or 5 below 1000.'

  sum = 1000.times.inject(0) do |acc, e|
    acc + (((e % 3).zero? || (e % 5).zero?) ? e : 0)
  end
  puts "The sum is #{sum}"
end

task :problem_2 do
  puts 'Each new term in the Fibonacci sequence is generated by adding the ' \
       'previous two terms. By starting with 1 and 2, the first 10 terms ' \
       'will be:'
  puts '1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...'
  puts 'By considering the terms in the Fibonacci sequence whose values ' \
       'do not exceed four million, find the sum of the even-valued terms.'

  def fib(n)
    return 0 if n <= 0
    n == 1 ? 1 : fib(n - 2) + fib(n - 1)
  end

  acc = []
  index = 1
  while true
    el = fib(index)
    el >= 4_000_000 ? break : acc << el
    index += 1
  end
  sum = acc.select { |x| (x % 2).zero? }.inject(:+)
  puts "The sum is #{sum}"
end

task :problem_3 do
  require 'prime'
  puts 'The prime factors of 13195 are 5, 7, 13 and 29.'
  puts 'What is the largest prime factor of the number 600851475143 ?'p

  def prime_factors(n)
    return [] if n < 2
    factors = []
    # Array of the prime numbers below number^2
    Prime.first(Math.sqrt(n)).each do |prime|
      break if prime**2 > n;
      while (n % prime).zero?
        factors << prime
        n /= prime
      end
    end
    factors << n if n > 1
    factors
  end

  largest = prime_factors(600851475143).max
  puts "The largest prime factor is #{largest}"
end

task :problem_4 do
  puts 'A palindromic number reads the same both ways. The largest ' \
       'palindrome made from the product of two 2-digit numbers is '\
       ' 9009 = 91 × 99.'
  puts 'Find the largest palindrome made from the product of two 3-digit ' \
       'numbers.'

  def palindromic?(n)
    string = n.to_s
    # string.reverse == string
    length = string.length
    (length.fdiv(2).ceil).times do |i|
      return false if !string[i].eql?(string[length-1-i])
    end
    true
  end

  palindromes = []
  (100..999).to_a.reverse_each do |x|
    (100..999).to_a.reverse_each do |y|
      if palindromic?(x * y)
        palindromes << { x: x, y: y, palindrome: (x * y) }
        break
      end
    end
  end
  largest = palindromes.max_by { |h| h[:palindrome]}
  puts "The largest palindrome is " \
       "#{largest[:palindrome]} = #{largest[:x]} * #{largest[:y]}"
end

task :problem_5 do
  puts '2520 is the smallest number that can be divided by each of the ' \
       'numbers from 1 to 10 without any remainder.'
  puts 'What is the smallest positive number that is evenly divisible by all ' \
       'of the numbers from 1 to 20?'

  # 1
  n = 1
  div = 3
  step = 1
  while div <= 20
    while true
      ary = (2..div).map { |d| n%d }.uniq
      if ary.count == 1 && ary[0].zero?
        step = n
        div += 1
        break
      else
        n += step
      end
    end
  end
  puts "The number is #{n}"
  # 2
  # [9, 5, 7, 11, 13, 16, 17, 19].inject(:*)
end
