require 'bundler/setup'
Bundler.require :default

task :problem_1 do
  puts 'If we list all the natural numbers below 10 that are multiples of ' \
       '3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.'
  puts 'Find the sum of all the multiples of 3 or 5 below 1000.'

  sum = 1000.times.inject(0) do |acc, e|
    acc + (((e % 3).zero? || (e % 5).zero?) ? e : 0)
  end
  puts "The sum is #{sum}"
end

task :problem_2 do
  puts 'Each new term in the Fibonacci sequence is generated by adding the ' \
       'previous two terms. By starting with 1 and 2, the first 10 terms ' \
       'will be:'
  puts '1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...'
  puts 'By considering the terms in the Fibonacci sequence whose values ' \
       'do not exceed four million, find the sum of the even-valued terms.'

  def fib(n)
    return 0 if n <= 0
    n == 1 ? 1 : fib(n - 2) + fib(n - 1)
  end

  acc = []
  index = 1
  while true
    el = fib(index)
    el >= 4_000_000 ? break : acc << el
    index += 1
  end
  sum = acc.select { |x| (x % 2).zero? }.inject(:+)
  puts "The sum is #{sum}"
end

task :problem_3 do
  require 'prime'
  puts 'The prime factors of 13195 are 5, 7, 13 and 29.'
  puts 'What is the largest prime factor of the number 600851475143 ?'

  def prime_factors(n)
    return [] if n < 2
    factors = []
    # Array of the prime numbers below number^2
    Prime.first(Math.sqrt(n)).each do |prime|
      break if prime**2 > n;
      while (n % prime).zero?
        factors << prime
        n /= prime
      end
    end
    factors << n if n > 1
    factors
  end

  largest = prime_factors(600851475143).max
  puts "The largest prime factor is #{largest}"
end
